### ISSUE TITLE
Input and output dynamic transformation

### ISSUE THREAD

**Issue by zhangbin006** [NTNU-IHB/PythonFMU#145]
Hello, may I ask, in the process of typing fMU format, the number of input and output is dynamically variable, but I don't know how to operate, do you have any good suggestions

**Comment by markaren** [comment]
I don't understand the question.
Once you create an FMU, the number of variables cannot be changed.
If you want to have say a dynamic vector as input you have to pre-allocate space for that yourself. That is create 1000 real outputs, of whom you might only use a fraction and set the remaining to 0. Then use an integer output to tell the user how many outputs are valid.
This is a general FMI thing and not specific to this library.

Please rephrase the question so that it is specific to PythonFMU.

**Comment by zhangbin006** [comment]
I see what you mean. Thank you, big man
