### ISSUE TITLE
FMI 3

### ISSUE THREAD

**Issue by StephenSmith25** [NTNU-IHB/PythonFMU#182]
Hey, thank you for this wonderful library. I was wondering if there are any plans to add support for FMI 3?

**Comment by markaren** [comment]
No plans, no. However, this project would hopefully be a good starting point for anyone out there interessting in the endeavour.

**Comment by mb-tt** [comment]
Hello @markaren,

I know the topic has been closed for a while, but since FMI 3 has evolved a lot, I want to ask if there are any changed plans?

The background why I ask is that we use PythonFMU as a kind of mocking framework in our tool ecu.test and together with the new data types/structures and also the layered standards we could provide even more features to our users.

Best regards,
Matthias

**Comment by markaren** [comment]
You might want to look into https://github.com/stephensmith25/PythonFMU3
