### ISSUE TITLE
Documentation folder should be nested within the extra folder

### ISSUE THREAD

**Issue by markaren** [NTNU-IHB/PythonFMU#88]
According to FMI 3.0, additional files not required to run the model should be placed in a folder named "extra". Perhaps we should stick with that also.

**Comment by fcollonval** [comment]
Two remarks on this one:

- we should be consistent with the standard. And as 3.0 is not yet released, we should stick to 2.0.
- I don't think this is the purpose of the`extra` folder. If you look at the [discussion](https://github.com/modelica/fmi-standard/pull/586/files) about the need, this sounds like tool related meta data rather than documentation.
This is supported by the fact that the documentation folder is kept unmodified in the [current draft](https://github.com/modelica/fmi-standard/blob/master/docs/2_3_fmu_distribution.adoc) and that the *extra* folder can be modified by the FMU user: 

> It is explicitly allowed for tools and users other than the original creator of an FMU to modify, add or delete entries in the extra/ directory without affecting the validity of the FMU in all other aspects.

**Comment by markaren** [comment]
Ah, wasn't aware that a `documentation` folder was mentioned in the standard. Closing.
